### ISSUE TITLE
New language for OWNERS?

### ISSUE THREAD

**Issue by campoy** [src-d/enry#180]
Should `OWNERS` file have their own language?

For instance, this file https://github.com/kubernetes/apimachinery/blob/master/Godeps/OWNERS returns an empty language selection.

According to [this post](https://codeengineered.com/blog/2017/kubernetes-owners-files/) it's a YAML file but we fail to identify it.

**Comment by bzz** [comment]
this is really nice, but enry relies on github/linguis for language detection - by design, it supports only the things that [linguist](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml) does [support](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) by auto generating Go code using exactly same heuristics as linguist.

So I would say this request need to be filed upstream.

**Comment by bzz** [comment]
Closing in favor of umbrella #181
