### ISSUE TITLE
executed test should match commit used to generate the data

### ISSUE THREAD

**Issue by mcuadros** [src-d/enry#47]
The CI is failing due to using the master branch of `linguist` with a code generated with another commit of `linguist`

**Comment by mcarmonaa** [comment]
@mcuadros Should we run tests against the same linguist's commit our files were generated or let it as a way to know linguist has been updated and we must generate files again?

**Comment by mcuadros** [comment]
Yep, we should run the test with the same version

**Comment by mcarmonaa** [comment]
Tests are failing because the linguist version in local differs from the linguist's commit our files were generated. TestLinguistCorpus() walk throw the .linguist/samples and takes the expected language from the directory name that contains all files related to a language.

Because linguist name for Perl 6 parsed from .linguist/lib/linguist/languages.yml has changed from "Perl6" to "Perl 6", the expected language in the test is "Perl 6", but with the files generated from a previous linguist's commit, Perl 6 in our map of languages is still parsed as "Perl6"

To run against the same commit our files were generated, we can generate another file that contains only a private variable with the linguist's commit all files have been generated:
`var linguistCommit= "b6460f8ed6b249281ada099ca28bd8f1230b8892"`

So we can have documented at a glance from what commit files were generated (although all generated files have a comment with this commit), and we can use this variable to download linguist to a temp directory, do a checkout to this commit and run tests like in internal/code-generator/generator's tests is done.
